# Generated by Django 4.2.5 on 2023-10-08 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_RUC', models.CharField(max_length=20)),
                ('Employee_cargo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.FloatField()),
                ('product_quantity', models.PositiveIntegerField()),
                ('order_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=200)),
                ('person_apellido_parterno', models.CharField(max_length=200)),
                ('person_apellido_materno', models.CharField(max_length=200)),
                ('person_address', models.CharField(max_length=200)),
                ('person_DNI', models.CharField(max_length=20)),
                ('person_phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_brand', models.CharField(max_length=200)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Supplier_name', models.CharField(max_length=200)),
                ('Supplier_phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.AddField(
            model_name='product',
            name='product_supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_supplier', to='api.supplier'),
        ),
        migrations.AddField(
            model_name='employee',
            name='Employee_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_person', to='api.person'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_person', to='api.person'),
        ),
    ]
