# Generated by Django 4.2.5 on 2023-10-26 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_pedido_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Employee_RUC',
        ),
    ]
