# Generated by Django 4.2.5 on 2023-10-08 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_customer_employee_pedido_person_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='product_quantity',
        ),
        migrations.AddField(
            model_name='pedido',
            name='product',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_pedido', to='api.product'),
        ),
    ]
