# Generated by Django 4.2.5 on 2023-10-26 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_pedido_product_pedido_customer_pedido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='person_DNI',
            new_name='person_DNI_RUC',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='person_name',
            new_name='person_name_RazonSocial',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='Supplier_name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='Supplier_phone',
        ),
        migrations.AddField(
            model_name='supplier',
            name='Supplier_person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_person', to='api.person'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='order_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_apellido_materno',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_apellido_parterno',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
